Build artifact

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -67,19 +67,26 @@ jobs:
           #role-session-name: GitHubActions
       - name: Manifest Generation
         run: |
+          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | shasum -a 256 ; then
-            echo "install.sh checksum failed"
-            exit 1
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
           fi
-          sh install.sh
+          BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
-          billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-              --aqua-key "${{ secrets.AQUA_KEY }}" \
-              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-              --artifact-path "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://asia-1.api.cloudsploit.com \
+            --artifact-path "my-image-name:${{ env.tag-version }}" 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1
